# Configuration settings

# Hyparameters
learning_rate : 0.01
momentum      : 0.9
epochs        : 10
batch_size    : 64
val_split     : 0.1
step_size     : 6
gamma         : 0.1
train_dataset : 'MNIST' # or 'MNIST'
loss_function : 'LSCE' # or 'LSCE'
optimizer_    : 'Adam' # or 'Adam'
augmentation  : True
use_batch_norm: True
pre_train     : False
fine_tune     : False
model_name    : 'best_model'
# Random seed
SEED          : 42

