import torch
import torchvision
from torch.utils.data import DataLoader
import torchvision.transforms as transforms
import torch.utils.data as data
from cleverhans.torch.attacks.fast_gradient_method import fast_gradient_method
import numpy as np
import math


def load_data(batch_size=64, val_split=0.2, data_path='.'):
    """Loads the CIFAR-10 dataset and prepares DataLoaders for training, validation, and testing.

    This function applies transformations, splits the training dataset into training and validation sets,
    and returns DataLoaders for efficient batch processing.

    Args:
        batch_size (int, optional): Number of samples per batch. Defaults to 64.
        val_split (float, optional): Proportion of training data to use for validation (0 to 1). Defaults to 0.2.
        data_path (str, optional): Directory path to download or load the CIFAR-10 dataset. Defaults to '.'.

    Returns:
        tuple: A tuple containing:
            - train_loader (DataLoader): DataLoader for the training set.
            - val_loader (DataLoader): DataLoader for the validation set.
            - test_loader (DataLoader): DataLoader for the test set.
    """

    # Define transforms
    transform = transforms.compose([
        transforms.ToTensor(),
        # transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.229, 0.224, 0.225]),
    ])

    # Load CIFAR-10 dataset
    train_ds = torchvision.datasets.CIFAR10(root=data_path, train=True, transform=transform, download=True)
    test_ds  = torchvision.datasets.CIFAR10(root=data_path, train=False, transform=transform,download=True)

    # Split train and validation datasets
    indices = np.arange(len(train_ds))
    np.random.shuffle(indices)
    val_size = math.floor(len(train_ds) * val_split)
    train_idx, val_idx = indices[val_size:], indices[:val_size]
    
    train_sampler = data.SubsetRandomSampler(train_idx)
    val_sampler   = data.SubsetRandomSampler(val_idx)

    # Create data loader
    train_loader = DataLoader(train_ds, batch_size, sampler=train_sampler)
    val_loader   = DataLoader(train_ds, batch_size, sampler=val_sampler)
    test_loader  = DataLoader(test_ds, batch_size, shuffle=True)

    return train_loader, val_loader, test_loader


def generate_adversary_samples(model, images, labels, loss_fn, epsilon=0.1, manual=False, num_pixels=10):
    """
    1. Generates adversarial examples using the Fast Gradient Sign Method (FGSM).
        FGSM attack perturbs the input images to maximize the model's loss, thereby generating adversarial examples.
        The attack can be performed using a manual implementation or CleverHans' `fast_gradient_method`.
    2. Add random noise by change some pixels of the image to a fixed value.


    Args:
        model (torch.nn.Module): The target model to attack.
        images (torch.Tensor): Input images.
        labels (torch.Tensor): True labels corresponding to the input images.
        loss_fn (callable): Loss function used for computing gradients.
        epsilon (float, optional): Magnitude of the perturbation. Defaults to 0.1.
        manual (bool, optional): Whether to use a manual FGSM implementation. Defaults to False.
        num_pixels (int, optional): The number of pixels that change. Defaults to 10.

    Returns:
        torch.Tensor: Adversarial examples generated by FGSM attack and random noise.
    """

    ### FGSM attack ###
    # clone().detach(): create a new copy without dependency on the computation graph.
    images = images.clone().detach().requires_grad_(True)
    batch_size, _, height, width = images.shape
    
    if manual:
        outputs = model(images)
        loss = loss_fn(outputs, labels)
        model.zero_grad()
        loss.backward()
        perturbation = torch.sign(images.grad) * epsilon
        adversary_images = images + perturbation
        # adversary_images = torch.clamp(adversary_images, -1, 1)
    else:
        adversary_images = fast_gradient_method(model, images, epsilon, np.inf)


    ### Add random noise ###
    # adversary_images = adversary_images.clone().detach()
    for i in range(batch_size):
        for _ in range(num_pixels):
            h, w = np.random.randint(0, height), np.random.randint(0, width)
            adversary_images[i, :, h, w] = 1.0  # Whitening the pixel.

    return adversary_images # .detach()
