# Configuration settings
learning_rate : 0.01
epochs    : 10
batch_size: 64 
val_split : 0.2
model_name: 'model'
epsilon   : 0.1
num_classes: 10
embedding_size: 128
adversary_training: False
use_circle_loss : False